name = "QuantumNaturalfPEPS"
uuid = "8cccb88f-824b-4ada-bd77-4bd123faaa4e"
authors = ["Konrad Schr√∂der <kschro21@smail.uni-koeln.de>"]
version = "0.1.0"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
QuantumNaturalGradient = "8d03283f-5cc1-4355-9ceb-601ddb1c7e78"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
